# Generated by Django 3.2 on 2022-03-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='home',
            new_name='name',
        ),
    ]
